import React from 'react';
import { DropDownListComponent } from '@syncfusion/ej2-react-dropdowns';
/* import the DropDownList dependency styles */
import '../../../node_modules/@syncfusion/ej2-inputs/styles/material.css';
import '../../../node_modules/@syncfusion/ej2-react-dropdowns/styles/material.css';
import './phoneInput.css';

export default function PhoneNumberInput(props) {
    const countryCodesWithLabels = [
        { text: 'AF (+93)', value: 'AF', label: 'Afghanistan' },
        { text: 'AL (+355)', value: 'AL', label: 'Albania' },
        { text: 'DZ (+213)', value: 'DZ', label: 'Algeria' },
        { text: 'AS (+1-684)', value: 'AS', label: 'American Samoa' },
        { text: 'AD (+376)', value: 'AD', label: 'Andorra' },
        { text: 'AO (+244)', value: 'AO', label: 'Angola' },
        { text: 'AI (+1-264)', value: 'AI', label: 'Anguilla' },
        { text: 'AG (+1-268)', value: 'AG', label: 'Antigua and Barbuda' },
        { text: 'AR (+54)', value: 'AR', label: 'Argentina' },
        { text: 'AM (+374)', value: 'AM', label: 'Armenia' },
        { text: 'AW (+297)', value: 'AW', label: 'Aruba' },
        { text: 'AU (+61)', value: 'AU', label: 'Australia' },
        { text: 'AT (+43)', value: 'AT', label: 'Austria' },
        { text: 'AZ (+994)', value: 'AZ', label: 'Azerbaijan' },
        { text: 'BS (+1-242)', value: 'BS', label: 'Bahamas' },
        { text: 'BH (+973)', value: 'BH', label: 'Bahrain' },
        { text: 'BD (+880)', value: 'BD', label: 'Bangladesh' },
        { text: 'BB (+1-246)', value: 'BB', label: 'Barbados' },
        { text: 'BY (+375)', value: 'BY', label: 'Belarus' },
        { text: 'BE (+32)', value: 'BE', label: 'Belgium' },
        { text: 'BZ (+501)', value: 'BZ', label: 'Belize' },
        { text: 'BJ (+229)', value: 'BJ', label: 'Benin' },
        { text: 'BT (+975)', value: 'BT', label: 'Bhutan' },
        { text: 'BO (+591)', value: 'BO', label: 'Bolivia' },
        { text: 'BA (+387)', value: 'BA', label: 'Bosnia and Herzegovina' },
        { text: 'BW (+267)', value: 'BW', label: 'Botswana' },
        { text: 'BR (+55)', value: 'BR', label: 'Brazil' },
        { text: 'BN (+673)', value: 'BN', label: 'Brunei Darussalam' },
        { text: 'BG (+359)', value: 'BG', label: 'Bulgaria' },
        { text: 'BF (+226)', value: 'BF', label: 'Burkina Faso' },
        { text: 'BI (+257)', value: 'BI', label: 'Burundi' },
        { text: 'KH (+855)', value: 'KH', label: 'Cambodia' },
        { text: 'CM (+237)', value: 'CM', label: 'Cameroon' },
        { text: 'CA (+1)', value: 'CA', label: 'Canada' },
        { text: 'CV (+238)', value: 'CV', label: 'Cape Verde' },
        { text: 'KY (+1-345)', value: 'KY', label: 'Cayman Islands' },
        { text: 'CF (+236)', value: 'CF', label: 'Central African Republic' },
        { text: 'TD (+235)', value: 'TD', label: 'Chad' },
        { text: 'CL (+56)', value: 'CL', label: 'Chile' },
        { text: 'CN (+86)', value: 'CN', label: 'China' },
        { text: 'CO (+57)', value: 'CO', label: 'Colombia' },
        { text: 'KM (+269)', value: 'KM', label: 'Comoros' },
        { text: 'CR (+506)', value: 'CR', label: 'Costa Rica' },
        { text: 'HR (+385)', value: 'HR', label: 'Croatia' },
        { text: 'CU (+53)', value: 'CU', label: 'Cuba' },
        { text: 'CW (+599)', value: 'CW', label: 'Curaçao' },
        { text: 'CY (+357)', value: 'CY', label: 'Cyprus' },
        { text: 'CZ (+420)', value: 'CZ', label: 'Czech Republic' },
        { text: 'CD (+243)', value: 'CD', label: 'Democratic Republic of the Congo' },
        { text: 'DK (+45)', value: 'DK', label: 'Denmark' },
        { text: 'DJ (+253)', value: 'DJ', label: 'Djibouti' },
        { text: 'DM (+1-767)', value: 'DM', label: 'Dominica' },
        { text: 'DO (+1-809)', value: 'DO', label: 'Dominican Republic' },
        { text: 'EC (+593)', value: 'EC', label: 'Ecuador' },
        { text: 'EG (+20)', value: 'EG', label: 'Egypt' },
        { text: 'SV (+503)', value: 'SV', label: 'El Salvador' },
        { text: 'GQ (+240)', value: 'GQ', label: 'Equatorial Guinea' },
        { text: 'ER (+291)', value: 'ER', label: 'Eritrea' },
        { text: 'EE (+372)', value: 'EE', label: 'Estonia' },
        { text: 'ET (+251)', value: 'ET', label: 'Ethiopia' },
        { text: 'FK (+500)', value: 'FK', label: 'Falkland Islands (Malvinas)' },
        { text: 'FO (+298)', value: 'FO', label: 'Faroe Islands' },
        { text: 'FJ (+679)', value: 'FJ', label: 'Fiji' },
        { text: 'FI (+358)', value: 'FI', label: 'Finland' },
        { text: 'FR (+33)', value: 'FR', label: 'France' },
        { text: 'PF (+689)', value: 'PF', label: 'French Polynesia' },
        { text: 'GA (+241)', value: 'GA', label: 'Gabon' },
        { text: 'GM (+220)', value: 'GM', label: 'Gambia' },
        { text: 'GE (+995)', value: 'GE', label: 'Georgia' },
        { text: 'DE (+49)', value: 'DE', label: 'Germany' },
        { text: 'GH (+233)', value: 'GH', label: 'Ghana' },
        { text: 'GI (+350)', value: 'GI', label: 'Gibraltar' },
        { text: 'GR (+30)', value: 'GR', label: 'Greece' },
        { text: 'GL (+299)', value: 'GL', label: 'Greenland' },
        { text: 'GD (+1-473)', value: 'GD', label: 'Grenada' },
        { text: 'GU (+1-671)', value: 'GU', label: 'Guam' },
        { text: 'GT (+502)', value: 'GT', label: 'Guatemala' },
        { text: 'GG (+44-1481)', value: 'GG', label: 'Guernsey' },
        { text: 'GN (+224)', value: 'GN', label: 'Guinea' },
        { text: 'GW (+245)', value: 'GW', label: 'Guinea-Bissau' },
        { text: 'GY (+592)', value: 'GY', label: 'Guyana' },
        { text: 'HT (+509)', value: 'HT', label: 'Haiti' },
        { text: 'HN (+504)', value: 'HN', label: 'Honduras' },
        { text: 'HK (+852)', value: 'HK', label: 'Hong Kong' },
        { text: 'HU (+36)', value: 'HU', label: 'Hungary' },
        { text: 'IS (+354)', value: 'IS', label: 'Iceland' },
        { text: 'IN (+91)', value: 'IN', label: 'India' },
        { text: 'ID (+62)', value: 'ID', label: 'Indonesia' },
        { text: 'IR (+98)', value: 'IR', label: 'Iran' },
        { text: 'IQ (+964)', value: 'IQ', label: 'Iraq' },
        { text: 'IE (+353)', value: 'IE', label: 'Ireland' },
        { text: 'IM (+44-1624)', value: 'IM', label: 'Isle of Man' },
        { text: 'IL (+972)', value: 'IL', label: 'Israel' },
        { text: 'IT (+39)', value: 'IT', label: 'Italy' },
        { text: 'CI (+225)', value: 'CI', label: 'Ivory Coast' },
        { text: 'JM (+1-876)', value: 'JM', label: 'Jamaica' },
        { text: 'JP (+81)', value: 'JP', label: 'Japan' },
        { text: 'JE (+44-1534)', value: 'JE', label: 'Jersey' },
        { text: 'JO (+962)', value: 'JO', label: 'Jordan' },
        { text: 'KZ (+7)', value: 'KZ', label: 'Kazakhstan' },
        { text: 'KE (+254)', value: 'KE', label: 'Kenya' },
        { text: 'KI (+686)', value: 'KI', label: 'Kiribati' },
        { text: 'KW (+965)', value: 'KW', label: 'Kuwait' },
        { text: 'KG (+996)', value: 'KG', label: 'Kyrgyzstan' },
        { text: 'LA (+856)', value: 'LA', label: 'Laos' },
        { text: 'LV (+371)', value: 'LV', label: 'Latvia' },
        { text: 'LB (+961)', value: 'LB', label: 'Lebanon' },
        { text: 'LS (+266)', value: 'LS', label: 'Lesotho' },
        { text: 'LR (+231)', value: 'LR', label: 'Liberia' },
        { text: 'LY (+218)', value: 'LY', label: 'Libya' },
        { text: 'LI (+423)', value: 'LI', label: 'Liechtenstein' },
        { text: 'LT (+370)', value: 'LT', label: 'Lithuania' },
        { text: 'LU (+352)', value: 'LU', label: 'Luxembourg' },
        { text: 'MO (+853)', value: 'MO', label: 'Macao' },
        { text: 'MK (+389)', value: 'MK', label: 'North Macedonia' },
        { text: 'MG (+261)', value: 'MG', label: 'Madagascar' },
        { text: 'MW (+265)', value: 'MW', label: 'Malawi' },
        { text: 'MY (+60)', value: 'MY', label: 'Malaysia' },
        { text: 'MV (+960)', value: 'MV', label: 'Maldives' },
        { text: 'ML (+223)', value: 'ML', label: 'Mali' },
        { text: 'MT (+356)', value: 'MT', label: 'Malta' },
        { text: 'MH (+692)', value: 'MH', label: 'Marshall Islands' },
        { text: 'MR (+222)', value: 'MR', label: 'Mauritania' },
        { text: 'MU (+230)', value: 'MU', label: 'Mauritius' },
        { text: 'YT (+262)', value: 'YT', label: 'Mayotte' },
        { text: 'MX (+52)', value: 'MX', label: 'Mexico' },
        { text: 'FM (+691)', value: 'FM', label: 'Micronesia' },
        { text: 'MD (+373)', value: 'MD', label: 'Moldova' },
        { text: 'MC (+377)', value: 'MC', label: 'Monaco' },
        { text: 'MN (+976)', value: 'MN', label: 'Mongolia' },
        { text: 'ME (+382)', value: 'ME', label: 'Montenegro' },
        { text: 'MS (+1-664)', value: 'MS', label: 'Montserrat' },
        { text: 'MA (+212)', value: 'MA', label: 'Morocco' },
        { text: 'MZ (+258)', value: 'MZ', label: 'Mozambique' },
        { text: 'MM (+95)', value: 'MM', label: 'Myanmar' },
        { text: 'NA (+264)', value: 'NA', label: 'Namibia' },
        { text: 'NR (+674)', value: 'NR', label: 'Nauru' },
        { text: 'NP (+977)', value: 'NP', label: 'Nepal' },
        { text: 'NL (+31)', value: 'NL', label: 'Netherlands' },
        { text: 'AN (+599)', value: 'AN', label: 'Netherlands Antilles' },
        { text: 'NC (+687)', value: 'NC', label: 'New Caledonia' },
        { text: 'NZ (+64)', value: 'NZ', label: 'New Zealand' },
        { text: 'NI (+505)', value: 'NI', label: 'Nicaragua' },
        { text: 'NE (+227)', value: 'NE', label: 'Niger' },
        { text: 'NG (+234)', value: 'NG', label: 'Nigeria' },
        { text: 'NU (+683)', value: 'NU', label: 'Niue' },
        { text: 'KP (+850)', value: 'KP', label: 'North Korea' },
        { text: 'MP (+1-670)', value: 'MP', label: 'Northern Mariana Islands' },
        { text: 'NO (+47)', value: 'NO', label: 'Norway' },
        { text: 'OM (+968)', value: 'OM', label: 'Oman' },
        { text: 'PK (+92)', value: 'PK', label: 'Pakistan' },
        { text: 'PW (+680)', value: 'PW', label: 'Palau' },
        { text: 'PS (+970)', value: 'PS', label: 'Palestine' },
        { text: 'PA (+507)', value: 'PA', label: 'Panama' },
        { text: 'PG (+675)', value: 'PG', label: 'Papua New Guinea' },
        { text: 'PY (+595)', value: 'PY', label: 'Paraguay' },
        { text: 'PE (+51)', value: 'PE', label: 'Peru' },
        { text: 'PH (+63)', value: 'PH', label: 'Philippines' },
        { text: 'PL (+48)', value: 'PL', label: 'Poland' },
        { text: 'PT (+351)', value: 'PT', label: 'Portugal' },
        { text: 'PR (+1-787)', value: 'PR', label: 'Puerto Rico' },
        { text: 'QA (+974)', value: 'QA', label: 'Qatar' },
        { text: 'CG (+242)', value: 'CG', label: 'Republic of the Congo' },
        { text: 'RO (+40)', value: 'RO', label: 'Romania' },
        { text: 'RU (+7)', value: 'RU', label: 'Russia' },
        { text: 'RW (+250)', value: 'RW', label: 'Rwanda' },
        { text: 'BL (+590)', value: 'BL', label: 'Saint Barthélemy' },
        { text: 'WS (+685)', value: 'WS', label: 'Samoa' },
        { text: 'SM (+378)', value: 'SM', label: 'San Marino' },
        { text: 'ST (+239)', value: 'ST', label: 'Sao Tome and Principe' },
        { text: 'SA (+966)', value: 'SA', label: 'Saudi Arabia' },
        { text: 'SN (+221)', value: 'SN', label: 'Senegal' },
        { text: 'RS (+381)', value: 'RS', label: 'Serbia' },
        { text: 'SC (+248)', value: 'SC', label: 'Seychelles' },
        { text: 'SL (+232)', value: 'SL', label: 'Sierra Leone' },
        { text: 'SG (+65)', value: 'SG', label: 'Singapore' },
        { text: 'SX (+1-721)', value: 'SX', label: 'Sint Maarten' },
        { text: 'SK (+421)', value: 'SK', label: 'Slovakia' },
        { text: 'SI (+386)', value: 'SI', label: 'Slovenia' },
        { text: 'SB (+677)', value: 'SB', label: 'Solomon Islands' },
        { text: 'SO (+252)', value: 'SO', label: 'Somalia' },
        { text: 'ZA (+27)', value: 'ZA', label: 'South Africa' },
        { text: 'KR (+82)', value: 'KR', label: 'South Korea' },
        { text: 'SS (+211)', value: 'SS', label: 'South Sudan' },
        { text: 'ES (+34)', value: 'ES', label: 'Spain' },
        { text: 'LK (+94)', value: 'LK', label: 'Sri Lanka' },
        { text: 'KN (+1-869)', value: 'KN', label: 'Saint Kitts and Nevis' },
        { text: 'LC (+1-758)', value: 'LC', label: 'Saint Lucia' },
        { text: 'MF (+590)', value: 'MF', label: 'Saint Martin' },
        { text: 'VC (+1-784)', value: 'VC', label: 'Saint Vincent and the Grenadines' },
        { text: 'SD (+249)', value: 'SD', label: 'Sudan' },
        { text: 'SR (+597)', value: 'SR', label: 'Suriname' },
        { text: 'SZ (+268)', value: 'SZ', label: 'Eswatini' },
        { text: 'SE (+46)', value: 'SE', label: 'Sweden' },
        { text: 'CH (+41)', value: 'CH', label: 'Switzerland' },
        { text: 'SY (+963)', value: 'SY', label: 'Syria' },
        { text: 'TW (+886)', value: 'TW', label: 'Taiwan' },
        { text: 'TJ (+992)', value: 'TJ', label: 'Tajikistan' },
        { text: 'TZ (+255)', value: 'TZ', label: 'Tanzania' },
        { text: 'TH (+66)', value: 'TH', label: 'Thailand' },
        { text: 'TL (+670)', value: 'TL', label: 'Timor-Leste' },
        { text: 'TG (+228)', value: 'TG', label: 'Togo' },
        { text: 'TK (+690)', value: 'TK', label: 'Tokelau' },
        { text: 'TO (+676)', value: 'TO', label: 'Tonga' },
        { text: 'TT (+1-868)', value: 'TT', label: 'Trinidad and Tobago' },
        { text: 'TN (+216)', value: 'TN', label: 'Tunisia' },
        { text: 'TR (+90)', value: 'TR', label: 'Turkey' },
        { text: 'TM (+993)', value: 'TM', label: 'Turkmenistan' },
        { text: 'TC (+1-649)', value: 'TC', label: 'Turks and Caicos Islands' },
        { text: 'TV (+688)', value: 'TV', label: 'Tuvalu' },
        { text: 'UG (+256)', value: 'UG', label: 'Uganda' },
        { text: 'UA (+380)', value: 'UA', label: 'Ukraine' },
        { text: 'AE (+971)', value: 'AE', label: 'United Arab Emirates' },
        { text: 'GB (+44)', value: 'GB', label: 'United Kingdom' },
        { text: 'US (+1)', value: 'US', label: 'United States' },
        { text: 'UY (+598)', value: 'UY', label: 'Uruguay' },
        { text: 'UZ (+998)', value: 'UZ', label: 'Uzbekistan' },
        { text: 'VU (+678)', value: 'VU', label: 'Vanuatu' },
        { text: 'VA (+379)', value: 'VA', label: 'Vatican City' },
        { text: 'VE (+58)', value: 'VE', label: 'Venezuela' },
        { text: 'VN (+84)', value: 'VN', label: 'Vietnam' },
        { text: 'VG (+1-284)', value: 'VG', label: 'British Virgin Islands' },
        { text: 'VI (+1-340)', value: 'VI', label: 'U.S. Virgin Islands' },
        { text: 'WF (+681)', value: 'WF', label: 'Wallis and Futuna' },
        { text: 'YE (+967)', value: 'YE', label: 'Yemen' },
        { text: 'ZM (+260)', value: 'ZM', label: 'Zambia' },
        { text: 'ZW (+263)', value: 'ZW', label: 'Zimbabwe' },
    ];

    return (
        <div className=''>
            <div>
                <p className='text-lg text-black font-medium'>Contact number</p>
            </div>
            <div
                style={{
                    display: 'flex',
                    alignItems: 'center',
                    width: `${props.isFrom == 'referral' && '100%'}`,
                }}
                className='border-lightGrey border rounded-md pr-2 pl-2 h-11 w-80 mt-[0.3rem] '
            >
                <DropDownListComponent
                    dataSource={countryCodesWithLabels}
                    fields={{ text: 'label', value: 'text' }}
                    itemTemplate={(data) => <span>{data.label}</span>}
                    valueTemplate={(data) => <span>{data.text}</span>}
                    placeholder='IN (+91)'
                    popupHeight='500px'
                    popupWidth='200px'
                    width={`${props?.isFrom == 'referral' ? '20%' : '100px'}`}
                    className='borderless'
                />
                <input
                    type='text'
                    placeholder='Your Contact Number'
                    name={props.name}
                    id={props.id}
                    style={{ flex: 1, marginLeft: 10, outline: 'none' }}
                />
            </div>
        </div>
    );
}
